
/* system start **/
export const SYSTEM_IS_LOGIN_SET = 'SYSTEM_IS_LOGIN_SET'
export const SYSTEM_MENU_SET = 'SYSTEM_MENU_SET'
export const SYSTEM_USERINFO_SET = 'SYSTEM_USERINFO_SET'
export const SYSTEM_SELECTMCHT_SET = "SYSTEM_SELECTMCHT_SET"
export const SYSTEM_ISSELECTMCHT_SET = "SYSTEM_ISSELECTMCHT_SET"
export const SYSTEM_OPENED_MENU_SET = 'SYSTEM_OPENED_MENU_SET'
export const SYSTEM_IS_SHOW_NOTICE = 'SYSTEM_IS_SHOW_NOTICE'
/* system end **/


